FROM jutge-org/base

# LaTeX (lite)
RUN apt-get --yes install texlive-latex-extra texlive-games texlive-pstricks

# Clear cache
RUN pip3 cache purge
RUN apt-get --yes clean

# Set user
USER worker
WORKDIR /home/worker
ENV USER=worker
ENV LANG=C.UTF-8